#!/usr/bin/env bash
set -euo pipefail

: ${APP_CLIENT_ID}
: ${APP_PRIVATE_KEY}
: ${GITHUB_REPOSITORY}
: ${GITHUB_API:=api.va.ghe.com}

# APP_PRIVATE_KEY may be a PEM file or the PEM content itself
if [ -f "${APP_PRIVATE_KEY}" ]; then APP_PRIVATE_KEY=$(cat "$APP_PRIVATE_KEY"); fi

b64() { openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n'; }

NOW=$(date +%s)
IAT=$((${NOW} - 60)) # Issues 60 seconds in the past
EXP=$((${NOW} + 600)) # Expires 10 minutes in the future

HEADER=$( echo -n '{"typ":"JWT","alg":"RS256"} ' | b64 )
PAYLOAD=$( echo -n "{ \"iat\":${IAT},\"exp\":${EXP},\"iss\":\"${APP_CLIENT_ID}\"}" | b64 )
HEADER_PAYLOAD="${HEADER}"."${PAYLOAD}"
SIGNATURE=$(openssl dgst -sha256 -sign <(echo -n "${APP_PRIVATE_KEY}") <(echo -n "${HEADER_PAYLOAD}") | b64)
JWT="${HEADER_PAYLOAD}"."${SIGNATURE}"
echo "$JWT"

echo API: ${GITHUB_API}
curl -L https://${GITHUB_API}/repos/${GITHUB_REPOSITORY}/installation \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  -H "Authorization: Bearer $JWT" \
  -o installation.json
jq . installation.json
INSTALLATION_ID=$(jq -r '.id' installation.json)
echo "Installation: $INSTALLATION_ID"
curl -Lf -X POST https://${GITHUB_API}/app/installations/$INSTALLATION_ID/access_tokens \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  -H "Authorization: Bearer $JWT" \
  -o token.json
jq . token.json
jq '.expires_at' token.json
jq '.permissions' token.json

