#!/usr/bin/env bash
set -euo pipefail

: ${APP_CLIENT_ID}
: ${APP_PRIVATE_KEY}

if [ -f ${APP_PRIVATE_KEY} ]; then APP_PRIVATE_KEY=$(cat $APP_PRIVATE_KEY); fi

b64() { openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n'; }

NOW=$(date +%s)
IAT=$((${NOW} - 60)) # Issues 60 seconds in the past
EXP=$((${NOW} + 600)) # Expires 10 minutes in the future

HEADER=$( echo -n '{"typ":"JWT","alg":"RS256"} ' | b64 )
PAYLOAD=$( echo -n "{ \"iat\":${IAT},\"exp\":${EXP},\"iss\":\"${APP_CLIENT_ID}\"}" | b64 )
HEADER_PAYLOAD="${HEADER}"."${PAYLOAD}"
SIGNATURE=$(openssl dgst -sha256 -sign <(echo -n "${APP_PRIVATE_KEY}") <(echo -n "${HEADER_PAYLOAD}") | b64)
JWT="${HEADER_PAYLOAD}"."${SIGNATURE}"
echo -n "$JWT"

