name: Build PR
run-name: ${{ github.event_name == 'pull_request' && format('PR #{0} Build', github.event.pull_request.number) || format('Branch {0} Build', github.ref_name) }}


permissions: write-all
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-with-compose.yaml
    secrets:
      compose-env: |
        PROJECT_REPO_USERNAME=${{ secrets.PROJECT_REPO_USERNAME }}
        PROJECT_REPO_PASSWORD=${{ secrets.PROJECT_REPO_PASSWORD }}
        PROJECT_REPO_URL=${{ vars.PROJECT_REPO_URL }}
        DELAY=10
      container-registry-username: ${{  github.actor }}
      container-registry-password: ${{ secrets.GITHUB_TOKEN }}
      app-client-id: ${{ secrets.APP_CLIENT_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
    with:
      container-registry-hostname: ghcr.io
      timeout-minutes: 30
      release: ${{ !startsWith(github.head_ref, 'release') }}
      # release: ${{ github.ref == 'refs/heads/main' }}
