#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit
if [ -n "${DEBUG:-}" ]; then DOCKER_PROGRESS=plain; set -x; fi

: ${DOCKER_PROGRESS:=none}
: ${DEFAULT_CACHE_DIRECTORY:=/tmp/docker-build-cache}

EXIT_ACTIONS=$(mktemp)
onExit() { echo "$1" >> $EXIT_ACTIONS; }
runExitActions() {
  tac $EXIT_ACTIONS | bash - > /dev/null 2>&1
  rm $EXIT_ACTIONS
}
trap runExitActions EXIT

APP_NAME=$(basename $(readlink -f $0))
declare -A COMMAND_HELP
declare -A COMMAND_ALIAS
registerCommand() {
  local delimeter="^"
  if [ "${#1}" == 1 ]; then delimiter=${1}; shift; fi
  local command="$1"  args="$2"
  shift 2
  COMMAND_HELP["$command"]+="${delimeter}${args:-}"
  while [ -n "${1:-}" ]
  do
    COMMAND_HELP["$command"]+="${delimeter}${1}"
    shift
  done
}

aliasCommand() {
  local command="${1}"
  shift
  while [ -n "${1:-}" ]
  do
    COMMAND_ALIAS["$1"]="$command"
    shift
  done
}

usageCommands() {
  for command in $(printf "%s\n" ${!COMMAND_HELP[@]} | sort); do usageCommand $command; done
}

usageCommand() {
  local command="$1"
  local spec delimeter parts
  spec="${COMMAND_HELP[$command]}"
  delimeter=${spec:0:1}
  readarray -t -d $delimeter parts <<< "${spec:1}"
  local argSummary helpStart=0
  if [ "${parts[0]:0:1}" == "[" ]
  then
    argSummary="${parts[0]}"
    helpStart=1
  fi
  echo "$command ${argSummary:-}"
  for ((i=$helpStart;i<${#parts[@]};i++)); do echo "  ${parts[$i]%$'\n'}"; done
  local aliases
  aliases=$(for name in ${!COMMAND_ALIAS[@]}; do if [ "${COMMAND_ALIAS[$name]}" == "$command" ]; then echo "$name"; fi; done | sort | paste -sd ',')
  if [ -n "${aliases:-}" ]; then echo "  alias: ${aliases}"; fi
}


#============================================================
log() { echo "$@" >&2; }
die() { echo "${1-}" >&2; exit 1; }

dieIfMissingValue() {
  local param=$1
  local value="${2:-}"
  if [ -z "${value:-}" ]; then die "Missing value for $param"; fi
}

requireParameterValue() {
  dieIfMissingValue "$@"
  echo "$2"
}

main() {
  if [ $# -eq 0 ]; then cmd-help "No command specified"; fi
  local command="${1}"
  shift
  if [ -n "${COMMAND_ALIAS[$command]:-}" ]; then command="${COMMAND_ALIAS[$command]}"; fi
  if [ -z "${COMMAND_HELP[$command]:-}" ]; then cmd-help "Unknown command: $command"; fi
  case "${1:-}" in
    -h|--help|help) usageCommand $command >&2 ; exit 1;;
  esac
  cmd-$command "$@"
}


#============================================================
registerCommand help "Print this help and exit"
cmd-help() {
cat<<EOF
$0 <command> [arguments]

Manage and work with Docker build mounted caches.
Docker cache mounts are not generally accessible with Docker tools.
This script provides the ability to export and import (or prime)
caches defined with:

  RUN --mount=type=cache,target=/fugazi/whatever

This enables RUN caches to be used with GitHub Actions Cache
as well with local development.

COMMANDS
$(usageCommands)

EOF
die "${1:-}"
}

#============================================================
registerCommand each-service  \
  "[--action import-cache|export-cache]" \
  "Perform the specified action for a list of service cache mounts" \
  "read from stdin. Each line must contain a service and target path." \
  "-a|--action <action>       Action to perform for each service mount" \
  "                           Allowed: import-cache, export-cache" \
  "-t|--target <mount-target> Mount target path from RUN --mount=type=cache,target=<path>" \
  "-d|--directory <dir>       Base directory where service cache content is stored" \
  "                           Default: ${DEFAULT_CACHE_DIRECTORY}" \
  "Input Format:" \
  "service /path/to/mount/target/directory" \
  "another-service /some/other/mount/target/directory" \
  "..."
cmd-each-service() {
  local action baseDirectory=${DEFAULT_CACHE_DIRECTORY}
  while [ -n "${1:-}" ]
  do
    case "${1}" in
      -a|--action) action=$(requireParameterValue $@); shift;;
      -d|--directory) baseDirectory=$(requireParameterValue $@); shift;;
      *) die "Unknown option: $1";;
    esac
    shift
  done
  dieIfMissingValue --action "${action:-}"
  case "$action" in
    *import*) action=import-cache;;
    *export*) action=export-cache;;
    *) die "Unknown action. Expected import-cache or export-cache, got: $action";;
  esac

  while read line
  do
    set -- $line
    if [ $# == 0 ]; then continue; fi
    if [ $# != 2 ]; then die "Expected line with 2 fields: service target (got $# fields: $line)"; fi
    local service=$1 target=$2
    cmd-$action --service $service --target $target --directory $baseDirectory
  done
}


#============================================================
registerCommand import-cache \
  "[--service <name> --target <mount-target>]" \
  "Import the cache contents for a run cache mount" \
  "-s|--service <name>        Docker compose service" \
  "-t|--target <mount-target> Mount target path from RUN --mount=type=cache,target=<path>" \
  "-d|--directory <dir>       Base directory where service cache content is stored" \
  "                           Default: ${DEFAULT_CACHE_DIRECTORY}"
aliasCommand import-cache i import
cmd-import-cache() {
  local service target baseDirectory=${DEFAULT_CACHE_DIRECTORY}
  while [ -n "${1:-}" ]
  do
    case "${1}" in
      -s|--service) service=$(requireParameterValue $@); shift;;
      -t|--target) target=$(requireParameterValue $@); shift;;
      -d|--directory) baseDirectory=$(requireParameterValue $@); shift;;
      *) die "Unknown option: $1";;
    esac
    shift
  done
  dieIfMissingValue --service "${service:-}"
  dieIfMissingValue --target "${target:-}"
  log "Importing $service cache $target"
  local mount cacheDir image
  cacheDir=$(cacheLocationForService $baseDirectory $service $target)
  if ! cacheDataAvailable $cacheDir; then return; fi
  mount=$(loadSavedMountConfiguration $cacheDir)
  log "Mounted using $mount"
  log "Importing $(ls -sh $cacheDir/build-cache.tar)"
  createImportImageToPrimeCache $target $cacheDir $mount
}

cacheDataAvailable() {
  local cacheDir="$1"
  if [ -f $cacheDir/mount -a -f $cacheDir/build-cache.tar ]; then return 0; fi
  log "Cache data not available"
  return 1
}
loadSavedMountConfiguration() {
  local cacheDir="$1"
  cat $cacheDir/mount
}
createImportImageToPrimeCache() {
  local target=$1 cacheDir=$2 mount=$3
  cd $cacheDir
  date > timestamp # used to force new layers and avoid layer caching
  cat > Dockerfile.import <<EOF
FROM busybox
COPY timestamp timestamp
RUN --mount=$mount --mount=type=bind,source=./build-cache.tar,target=/tmp/build-cache.tar tar x -C $target -f /tmp/build-cache.tar
EOF
  local tag=run-mount-cache-import:${target////}
  docker buildx build --load --file Dockerfile.import --progress $DOCKER_PROGRESS --tag $tag .
  onExit "docker rmi $tag"
}

#============================================================
registerCommand export-cache \
  "[--service <name> --target <mount-target>]" \
  "Export the cache contents of a run cache mount" \
  "-s|--service <name>        Docker compose service" \
  "-t|--target <mount-target> Mount target path from RUN --mount=type=cache,target=<path>" \
  "-d|--directory <dir>       Base directory where service cache content is stored" \
  "                           Default: ${DEFAULT_CACHE_DIRECTORY}"
aliasCommand export-cache e export
cmd-export-cache() {
  local service target baseDirectory=${DEFAULT_CACHE_DIRECTORY}
  while [ -n "${1:-}" ]
  do
    case "${1}" in
      -s|--service) service=$(requireParameterValue $@); shift;;
      -t|--target) target=$(requireParameterValue $@); shift;;
      -d|--directory) baseDirectory=$(requireParameterValue $@); shift;;
      *) die "Unknown option: $1";;
    esac
    shift
  done
  dieIfMissingValue --service "${service:-}"
  dieIfMissingValue --target "${target:-}"
  log "Exporting $service cache $target"
  local mount cacheDir image
  mount=$(exportMountFromDockerfileForService $service $target)
  log "Mounted using $mount"
  cacheDir=$(recreateDirectory $(cacheLocationForService $baseDirectory $service $target))
  image=$(createExportImage $target $cacheDir $mount)
  exportCacheFromImage $image $cacheDir
  saveMountConfigurationForImport "$mount" $cacheDir
  log "Exported $(ls -sh $cacheDir/build-cache.tar)"
}

saveMountConfigurationForImport() {
  local mount=$1 cacheDir=$2
  echo -n "$mount" > $cacheDir/mount
}

exportCacheFromImage() {
  local image=$1 cacheDir=$2
  local container
  container=$(docker create $image)
  onExit "docker rm $container"
  docker cp -qL $container:/tmp/build-cache.tar $cacheDir/build-cache.tar
}

createExportImage() {
  local target=$1 cacheDir=$2 mount=$3
  cd $cacheDir
  date > timestamp # used to force new layers and avoid layer caching
  cat > Dockerfile.export <<EOF
FROM busybox
COPY timestamp timestamp
RUN mkdir -p $(dirname $target)
RUN --mount=$mount tar c -C $target -f /tmp/build-cache.tar .
EOF
  local tag=run-mount-cache-export:${target////}
  docker buildx build --load --file Dockerfile.export --progress $DOCKER_PROGRESS --tag $tag .
  onExit "docker rmi $tag"
  echo $tag
}

cacheLocationForService() { echo -n "$1/$2/${3////.}"; }

recreateDirectory() { if [ -d $1 ]; then rm -rf $1; fi; mkdir -p $1; echo $1; }

exportMountFromDockerfileForService() {
  local service=$1 target=$2
  local dockerfile mount
  dockerfile=$(dockerfileForService $service)
  mount=$(cacheMountInDockerfileForTarget $dockerfile $target)
  mount=$(evaluateMountVariablesForService $service $mount)
  simplifyMountConfigurationForExportUse $mount
}
dockerfileForService() {
  local service=${1}
  local dockerfile
  dockerfile=$(docker compose config --format json \
    | jq -r --arg s $service \
    '.services|to_entries[]|select(.key == $s)|.value.build.context + "/" + .value.build.dockerfile')
  if [ -z "${dockerfile:-}" ]; then die "Service not found: $service"; fi
  if [ ! -f "$dockerfile" ]; then die "File not found: $dockerfile"; fi
  echo $dockerfile
}
cacheMountInDockerfileForTarget() {
  local dockerfile=${1} target=${2}
  local mount
  mount=$(grep -E -- '--mount=.*type=cache' $dockerfile \
    | grep -E "(target|dst|destination)=$target" \
    | sed -e 's/.*--mount=//' -e 's/ *\\\?$//') \
    || true
  if [ -z "${mount:-}" ]; then die "Mount not found for target $target in $dockerfile"; fi
  echo "$mount"
}
evaluateMountVariablesForService() {
  local service="${1}" mount="${2}"
  # could have build arg variables, we need to evaluate it in the context of the service container
  docker compose run --rm --no-deps -qT --entrypoint sh $service -c "echo -n $mount" 2>/dev/null
}
simplifyMountConfigurationForExportUse() {
  local mount="${1}"
  local result="type=cache"
  IFS=, read -r -a opts <<< $mount
  for opt in ${opts[@]}
  do
    case "$opt" in
      id=*|gid=*|uid=*) result+=",$opt";;
      target=*|dst=*|destination=*) result+=",target=${opt#*=}";;
    esac
  done
  echo "$result"
}


#============================================================
main "$@"
